Deployment attempt: 15

diff --git a/.github/workflows/azure-webapps.yml b/.github/workflows/azure-webapps.yml
--- a/.github/workflows/azure-webapps.yml
+++ b/.github/workflows/azure-webapps.yml
@@ -61,16 +61,22 @@ jobs:
             exit 1
           fi
           npx playwright --version
-
       - name: Publish
         run: dotnet publish ./Uxcheckmate/Uxcheckmate_Main/Uxcheckmate_Main.csproj --configuration Release --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
 
       - name: Copy Playwright Browsers to publish folder
         run: |
           echo "📁 Copying Playwright browsers to publish folder..."
-          mkdir -p '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/playwright/lol/.cache'
+          mkdir -p '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/playwright/.cache'
           cp -r ~/.cache/ms-playwright '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/playwright/.cache/ms-playwright'
-
+      - name: Check copied browser binaries
+        run: |
+          echo "🔍 Checking if Playwright browsers exist in publish folder..."
+          if [ -d "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/playwright/.cache/ms-playwright" ]; then
+            echo "✅ Browser binaries copied successfully."
+          else
+            echo "❌ Browser binaries missing!" && exit 1
+          fi
       - name: Deployment
         uses: azure/webapps-deploy@v2
         with:
